### ISSUE TITLE
Disappearing plots on graphics trace

### ISSUE THREAD

**Issue by pesky-cpu** [TOSUN-Shanghai/TSMaster#34]
**Bug:** Below video is of a offline log replay, there's an issue with the graph line disappearing after a certain number of additional points

https://user-images.githubusercontent.com/27743747/149234256-2dbf4746-6bbc-41f5-a48b-2d8dd1603f14.mp4

**Comment by freshhope** [comment]
that is because the internal ring buffer limit is reached, you can enlarge the buffer size, from 100000 to 1000000, or even larger:
![image](https://user-images.githubusercontent.com/16358754/149238022-7d8a202a-4764-4d48-8bd1-7ad148da797b.png)

by the way, two solutions are currently under development:

[1] use hard disk to cache all data points

[2] x64 version
the current implementation is x86 architecture, thus max points cannot be larger than 4294967295, I am struggling with x64 version, unliminted number of data points can be stored into memory when x64 comes out
