### ISSUE TITLE
Diagnostic ISO TP - Add Enter Key action

### ISSUE THREAD

**Issue by totocaca123** [TOSUN-Shanghai/TSMaster#53]
When I type manually my commands and press key "Enter", my command in not executed. I need to press the button execute with the mouse.
After pressing "Enter" key, the command line need to be cleared to allow me to put the next command

Moreover, command data needs to be displayed as padded "10 01" insted of "1001" in the input text.

![image](https://user-images.githubusercontent.com/42418580/167029873-ed811fc1-9f9e-4928-af42-d83266c4bbbe.png)

**Comment by XieYY135** [comment]
This feature will be supported in recent releases

**Comment by XieYY135** [comment]
![image](https://user-images.githubusercontent.com/12216193/167231686-5148c9b1-5aa7-421e-89e9-820bb478b6d2.png)

**Comment by dragoudin** [comment]
I tested this feature in version 2022-08-19

- When I type my command and I press enter, diagnostic command is padded : Issue corrected
- But the command is not executed (I have to press button Execute to send my request).

This issue is partially corrected and execution of command is missing (when I put my command and press enter, it's more intuitive and faster than using mouse to press button Execute).
So this issue needs to be reopened
